name: Test Callable
on:
  workflow_call:
    inputs:
      message:
        type: string
        required: true
    outputs:
      result:
        description: 'Test result'
        value: ${{ jobs.echo-job.outputs.result }}

permissions:
  contents: read
  packages: write

jobs:
  echo-job:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.out.outputs.result }}
    steps:
      - run: echo "${{ inputs.message }}"
      - id: out
        run: echo "result=ok" >> $GITHUB_OUTPUT
